#debug: true

# PROFILES
## dev | prod | test
spring:
  profiles.active: dev
  main.show_banner: false
  application.name: commondata-service
  jackson:
     date-format: yyyy-MM-dd HH:mm:ss
     time-zone: GMT+08:00

# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  port: 8100
  session-timeout:  30
#  context-path:
  tomcat.max-threads:  0
  tomcat.uri-encoding:  UTF-8
  undertow.accesslog.enabled: false
  undertow.accesslog.dir: target/logs
  undertow.accesslog.pattern: combined
  compression.enabled: true
  compression.min-response-size: 1
logging:
  file: ${spring.application.name}.log
  ROOT: INFO
  level.com.cnotes: DEBUG
  level.org.springframework.web: DEBUG
  level.org.springframework.transaction: INFO

spring.data.mongodb:
#      uri: mongodb://120.55.120.173/51qed
      uri: mongodb://localhost/qed
      username: qed
      password: qed
#      repositories.enabled: true

